/**
 * ReceiptStore -- Audit log API.
 *
 * Phase 1: InMemoryReceiptStore (human actions only).
 * Phase 3: SupabaseReceiptStore (persisted, AI actions with rationale).
 *
 * The receipt schema is the 12-field design from the AIA assessment
 * extended with AI rationale fields per AD-6. Only meaningful actions
 * generate receipts. Expected volume: 5-15 per session.
 *
 * References: AD-6 (Receipt System), AD-7 interface #3,
 * IA Assessment Section 5 (Evidence Ledger Structure)
 */

import type {
  Actor,
  AppIdentifier,
  EventType,
  ISOTimestamp,
  ReceiptSource,
  Severity,
  SpatialLocation,
  Unsubscribe,
} from './types'
import type { CameraTarget } from './camera-controller'

// ============================================================================
// AI Receipt Metadata
// ============================================================================

/**
 * Additional fields for AI-initiated actions.
 * Null for human-initiated receipts. Populated in Phase 3.
 *
 * Per AD-6: "AI receipts include additional fields: prompt, reasoning,
 * confidence, alternatives considered, provider, latency."
 */
export interface AIReceiptMetadata {
  /** The prompt or input that triggered the AI action. */
  readonly prompt: string
  /** AI's reasoning for the action taken. */
  readonly reasoning: string
  /** Confidence score from 0.0 (no confidence) to 1.0 (certain). */
  readonly confidence: number
  /** Other options the AI considered but did not select. */
  readonly alternativesConsidered: readonly string[]
  /** Which AI provider executed this action. */
  readonly provider: 'ollama' | 'claude' | 'rule-engine' | 'pattern-matcher'
  /** End-to-end AI response time in milliseconds. */
  readonly latencyMs: number
  /** Model identifier (e.g., "llama3.2", "claude-sonnet-4-20250514"). Null for non-LLM providers. */
  readonly modelId: string | null
}

// ============================================================================
// Launch Receipt (12-field schema + AI extension)
// ============================================================================

/**
 * Immutable record of a meaningful Launch event.
 *
 * Per IA Assessment Section 5:
 * - id: UUID v7 (time-sortable)
 * - correlationId: links related events across Launch + apps
 * - source: which app/Launch generated the event
 * - eventType: classification for faceted filtering
 * - severity: urgency level
 * - summary: human-readable, max 120 chars
 * - detail: structured payload, app-specific
 * - location: spatial context (zoom level, district, station)
 * - timestamp: ISO 8601 with milliseconds
 * - durationMs: for events with duration
 * - actor: human/ai/system attribution
 * - aiMetadata: AI rationale (null for human actions)
 */
export interface LaunchReceipt {
  /** UUID v7 (time-sortable). Generated by the store. */
  readonly id: string
  /** Links related events across Launch + apps. Null for uncorrelated events. */
  readonly correlationId: string | null
  /** Which app or 'launch' generated this event. */
  readonly source: ReceiptSource
  /** Event classification for Evidence Ledger filtering. */
  readonly eventType: EventType
  /** Urgency level. */
  readonly severity: Severity
  /** Human-readable summary, max 120 characters. */
  readonly summary: string
  /** Structured detail payload. App-specific. Rendered as collapsible raw data. */
  readonly detail: Record<string, unknown> | null
  /** Where in the Launch this event originated. */
  readonly location: SpatialLocation
  /** ISO 8601 with milliseconds. */
  readonly timestamp: ISOTimestamp
  /** Duration for events that span time. Null for instantaneous events. */
  readonly durationMs: number | null
  /** Who initiated this event. */
  readonly actor: Actor
  /** AI rationale fields. Null for human/system-initiated events. */
  readonly aiMetadata: AIReceiptMetadata | null
}

// ============================================================================
// Receipt Input (what consumers provide to record())
// ============================================================================

/**
 * Input for creating a new receipt. The store generates `id` and `timestamp`.
 */
export interface ReceiptInput {
  readonly correlationId?: string | null
  readonly source: ReceiptSource
  readonly eventType: EventType
  readonly severity: Severity
  readonly summary: string
  readonly detail?: Record<string, unknown> | null
  readonly location: SpatialLocation
  readonly durationMs?: number | null
  readonly actor: Actor
  readonly aiMetadata?: AIReceiptMetadata | null
  // --- New fields (WS-3.1) ---
  /**
   * Camera target for receipt rehydration navigation.
   * When a receipt is clicked in the Evidence Ledger, the viewport
   * navigates to this target to restore spatial context.
   *
   * Added by WS-3.1 to resolve the gap between WS-1.7 and WS-2.6.
   * The useReceiptStamp hook (WS-2.6) already populates this field.
   */
  readonly target?: CameraTarget | null
  /**
   * Searchable tags for faceted filtering.
   * Typically: [districtId, stationName, actionId].
   *
   * Added by WS-3.1 to resolve the gap between WS-1.7 and WS-2.6.
   */
  readonly tags?: readonly string[] | null
  /**
   * Links to a system snapshot captured at receipt creation time.
   * Used by Evidence Ledger for "then vs. now" metric comparison.
   *
   * Added by WS-3.1 for receipt rehydration support.
   */
  readonly snapshotId?: string | null
}

// ============================================================================
// Receipt Filters (for Evidence Ledger queries)
// ============================================================================

/**
 * Filter criteria for receipt queries.
 * Maps directly to the 4 Evidence Ledger facets from IA Assessment Section 5.
 */
export interface ReceiptFilters {
  /** Filter by source app(s). Empty = all sources. */
  readonly sources?: readonly ReceiptSource[]
  /** Filter by event type(s). Empty = all types. */
  readonly eventTypes?: readonly EventType[]
  /** Filter by severity level(s). Empty = all severities. */
  readonly severities?: readonly Severity[]
  /** Filter by time range. */
  readonly timeRange?: {
    readonly start: ISOTimestamp
    readonly end: ISOTimestamp
  }
  /** Filter by actor type. */
  readonly actor?: Actor
  /** Filter by district. */
  readonly district?: AppIdentifier
  /** Full-text search across summaries. */
  readonly search?: string
  /** Maximum number of results. Default: 100. */
  readonly limit?: number
  /** Offset for pagination. Default: 0. */
  readonly offset?: number
}

// ============================================================================
// ReceiptStore Interface
// ============================================================================

export interface ReceiptStore {
  /**
   * Record a new receipt. The store generates the `id` (UUID v7) and
   * `timestamp` (current time). Returns the complete receipt.
   */
  record(input: ReceiptInput): Promise<LaunchReceipt>

  /**
   * Query receipts with filtering and pagination.
   * Results are ordered by timestamp descending (newest first).
   */
  query(filters?: ReceiptFilters): Promise<LaunchReceipt[]>

  /** Get a single receipt by ID. Returns null if not found. */
  getById(id: string): Promise<LaunchReceipt | null>

  /**
   * Get all receipts sharing a correlation ID.
   * Used to display causal chains in the Evidence Ledger.
   */
  getByCorrelation(correlationId: string): Promise<LaunchReceipt[]>

  /** Get the total count of receipts matching the given filters. */
  count(filters?: ReceiptFilters): Promise<number>

  /**
   * Subscribe to new receipts as they are recorded.
   * The listener is called with each new receipt immediately after storage.
   */
  subscribe(listener: (receipt: LaunchReceipt) => void): Unsubscribe
}

// ============================================================================
// Phase 1 Implementation: InMemoryReceiptStore
// ============================================================================

/**
 * Phase 1 ReceiptStore. Holds receipts in an in-memory array.
 *
 * Limitations:
 * - Receipts are lost on page refresh (no persistence)
 * - No full-text search (search filter does basic string.includes())
 * - No UUID v7 (uses crypto.randomUUID() which is v4)
 *
 * Phase 3 replacement: SupabaseReceiptStore (WS-3.1) persists to the
 * `launch_receipts` table with proper UUID v7 and full-text search.
 */
export class InMemoryReceiptStore implements ReceiptStore {
  private receipts: LaunchReceipt[] = []
  private listeners: Set<(receipt: LaunchReceipt) => void> = new Set()

  async record(input: ReceiptInput): Promise<LaunchReceipt> {
    const receipt: LaunchReceipt = {
      id: crypto.randomUUID(),
      correlationId: input.correlationId ?? null,
      source: input.source,
      eventType: input.eventType,
      severity: input.severity,
      summary: input.summary.slice(0, 120),
      detail: input.detail ?? null,
      location: input.location,
      timestamp: new Date().toISOString(),
      durationMs: input.durationMs ?? null,
      actor: input.actor,
      aiMetadata: input.aiMetadata ?? null,
    }

    this.receipts.unshift(receipt) // newest first

    for (const listener of this.listeners) {
      listener(receipt)
    }

    return receipt
  }

  async query(filters?: ReceiptFilters): Promise<LaunchReceipt[]> {
    let results = [...this.receipts]

    if (filters) {
      if (filters.sources && filters.sources.length > 0) {
        const sources = new Set(filters.sources)
        results = results.filter((r) => sources.has(r.source))
      }
      if (filters.eventTypes && filters.eventTypes.length > 0) {
        const types = new Set(filters.eventTypes)
        results = results.filter((r) => types.has(r.eventType))
      }
      if (filters.severities && filters.severities.length > 0) {
        const sevs = new Set(filters.severities)
        results = results.filter((r) => sevs.has(r.severity))
      }
      if (filters.timeRange) {
        const start = new Date(filters.timeRange.start).getTime()
        const end = new Date(filters.timeRange.end).getTime()
        results = results.filter((r) => {
          const t = new Date(r.timestamp).getTime()
          return t >= start && t <= end
        })
      }
      if (filters.actor) {
        results = results.filter((r) => r.actor === filters.actor)
      }
      if (filters.district) {
        results = results.filter((r) => r.location.district === filters.district)
      }
      if (filters.search) {
        const lower = filters.search.toLowerCase()
        results = results.filter((r) => r.summary.toLowerCase().includes(lower))
      }

      const offset = filters.offset ?? 0
      const limit = filters.limit ?? 100
      results = results.slice(offset, offset + limit)
    }

    return results
  }

  async getById(id: string): Promise<LaunchReceipt | null> {
    return this.receipts.find((r) => r.id === id) ?? null
  }

  async getByCorrelation(correlationId: string): Promise<LaunchReceipt[]> {
    return this.receipts.filter((r) => r.correlationId === correlationId)
  }

  async count(filters?: ReceiptFilters): Promise<number> {
    if (!filters) return this.receipts.length
    const results = await this.query({ ...filters, limit: undefined, offset: undefined })
    return results.length
  }

  subscribe(listener: (receipt: LaunchReceipt) => void): Unsubscribe {
    this.listeners.add(listener)
    return () => {
      this.listeners.delete(listener)
    }
  }
}
