/**
 * TypeScript types for the Supabase database schema.
 *
 * These types map 1:1 to the SQL schema in supabase/migrations/.
 * They are used by the Supabase client for type-safe queries.
 *
 * In a production project, these would be auto-generated by
 * `supabase gen types typescript`. For this project, they are
 * hand-maintained to avoid a CLI dependency.
 *
 * References:
 * - 001_launch_receipts.sql
 * - 002_launch_snapshots.sql
 */

// ============================================================================
// Database Schema Type (Supabase convention)
// ============================================================================

export interface Database {
  public: {
    Tables: {
      launch_receipts: {
        Row: LaunchReceiptRow
        Insert: LaunchReceiptInsert
        Update: LaunchReceiptUpdate
      }
      launch_snapshots: {
        Row: LaunchSnapshotRow
        Insert: LaunchSnapshotInsert
        Update: LaunchSnapshotUpdate
      }
    }
    Views: Record<string, never>
    Functions: {
      prune_old_periodic_snapshots: {
        Args: { retention_days?: number }
        Returns: number
      }
    }
    Enums: Record<string, never>
  }
}

// ============================================================================
// launch_receipts
// ============================================================================

/** Row type: what you get back from a SELECT. */
export interface LaunchReceiptRow {
  id: string // UUID v7
  correlation_id: string | null // UUID
  source: string // ReceiptSource
  event_type: string // EventType
  severity: string // Severity
  summary: string // max 120 chars
  detail: Record<string, unknown> | null // JSONB
  location: {
    // JSONB
    semanticLevel: string
    district: string | null
    station: string | null
  }
  timestamp: string // TIMESTAMPTZ (ISO 8601)
  duration_ms: number | null
  actor: string // Actor
  ai_metadata: {
    // JSONB
    prompt: string
    reasoning: string
    confidence: number
    alternativesConsidered: string[]
    provider: string
    latencyMs: number
    modelId: string | null
  } | null
  target: Record<string, unknown> | null // JSONB (CameraTarget)
  tags: string[] | null
  snapshot_id: string | null // UUID
  created_at: string // TIMESTAMPTZ
}

/** Insert type: what you provide for an INSERT. */
export interface LaunchReceiptInsert {
  id: string
  correlation_id?: string | null
  source: string
  event_type: string
  severity: string
  summary: string
  detail?: Record<string, unknown> | null
  location: Record<string, unknown>
  timestamp: string
  duration_ms?: number | null
  actor: string
  ai_metadata?: Record<string, unknown> | null
  target?: Record<string, unknown> | null
  tags?: string[] | null
  snapshot_id?: string | null
  created_at?: string
}

/** Update type: all fields optional. */
export type LaunchReceiptUpdate = Partial<LaunchReceiptInsert>

// ============================================================================
// launch_snapshots
// ============================================================================

/** Row type: what you get back from a SELECT. */
export interface LaunchSnapshotRow {
  id: string // UUID v7
  timestamp: string // TIMESTAMPTZ
  trigger: string // 'receipt' | 'periodic' | 'manual'
  data: Record<string, unknown> // JSONB (SystemSnapshot)
  receipt_id: string | null // UUID
  created_at: string // TIMESTAMPTZ
}

/** Insert type: what you provide for an INSERT. */
export interface LaunchSnapshotInsert {
  id: string
  timestamp?: string
  trigger: string
  data: Record<string, unknown>
  receipt_id?: string | null
  created_at?: string
}

/** Update type: all fields optional. */
export type LaunchSnapshotUpdate = Partial<LaunchSnapshotInsert>
