/**
 * TypeScript types for the Supabase database schema.
 *
 * These types map 1:1 to the SQL schema in supabase/migrations/.
 * They are used by the Supabase client for type-safe queries.
 *
 * In a production project, these would be auto-generated by
 * `supabase gen types typescript`. For this project, they are
 * hand-maintained to avoid a CLI dependency.
 *
 * References:
 * - 001_launch_receipts.sql
 * - 002_launch_snapshots.sql
 */

// ============================================================================
// Database Schema Type (Supabase convention)
// ============================================================================

export interface Database {
  public: {
    Tables: {
      launch_receipts: {
        Row: LaunchReceiptRow
        Insert: LaunchReceiptInsert
        Update: LaunchReceiptUpdate
      }
      launch_snapshots: {
        Row: LaunchSnapshotRow
        Insert: LaunchSnapshotInsert
        Update: LaunchSnapshotUpdate
      }
      intel_sources: {
        Row: IntelSourceRow
        Insert: Omit<IntelSourceRow, never>
        Update: Partial<IntelSourceRow>
      }
      intel_normalized: {
        Row: IntelNormalizedRow
        Insert: Omit<IntelNormalizedRow, never>
        Update: Partial<IntelNormalizedRow>
      }
    }
    Views: Record<string, never>
    Functions: {
      prune_old_periodic_snapshots: {
        Args: { retention_days?: number }
        Returns: number
      }
    }
    Enums: Record<string, never>
  }
}

// ============================================================================
// launch_receipts
// ============================================================================

/** Row type: what you get back from a SELECT. */
export interface LaunchReceiptRow {
  id: string // UUID v7
  correlation_id: string | null // UUID
  source: string // ReceiptSource
  event_type: string // EventType
  severity: string // Severity
  summary: string // max 120 chars
  detail: Record<string, unknown> | null // JSONB
  location: {
    // JSONB
    semanticLevel: string
    district: string | null
    station: string | null
  }
  timestamp: string // TIMESTAMPTZ (ISO 8601)
  duration_ms: number | null
  actor: string // Actor
  ai_metadata: {
    // JSONB
    prompt: string
    reasoning: string
    confidence: number
    alternativesConsidered: string[]
    provider: string
    latencyMs: number
    modelId: string | null
  } | null
  target: Record<string, unknown> | null // JSONB (CameraTarget)
  tags: string[] | null
  snapshot_id: string | null // UUID
  created_at: string // TIMESTAMPTZ
}

/** Insert type: what you provide for an INSERT. */
export interface LaunchReceiptInsert {
  id: string
  correlation_id?: string | null
  source: string
  event_type: string
  severity: string
  summary: string
  detail?: Record<string, unknown> | null
  location: Record<string, unknown>
  timestamp: string
  duration_ms?: number | null
  actor: string
  ai_metadata?: Record<string, unknown> | null
  target?: Record<string, unknown> | null
  tags?: string[] | null
  snapshot_id?: string | null
  created_at?: string
}

/** Update type: all fields optional. */
export type LaunchReceiptUpdate = Partial<LaunchReceiptInsert>

// ============================================================================
// launch_snapshots
// ============================================================================

/** Row type: what you get back from a SELECT. */
export interface LaunchSnapshotRow {
  id: string // UUID v7
  timestamp: string // TIMESTAMPTZ
  trigger: string // 'receipt' | 'periodic' | 'manual'
  data: Record<string, unknown> // JSONB (SystemSnapshot)
  receipt_id: string | null // UUID
  created_at: string // TIMESTAMPTZ
}

/** Insert type: what you provide for an INSERT. */
export interface LaunchSnapshotInsert {
  id: string
  timestamp?: string
  trigger: string
  data: Record<string, unknown>
  receipt_id?: string | null
  created_at?: string
}

/** Update type: all fields optional. */
export type LaunchSnapshotUpdate = Partial<LaunchSnapshotInsert>

// ============================================================================
// intel_sources
// ============================================================================

/**
 * Row type for intel_sources table (SELECT result).
 *
 * Represents a single intelligence feed configured in TarvaRI.
 * The `status` and `category` fields use `string` (not union types) to
 * tolerate unexpected values from the database. Narrower types
 * (`SourceStatus`, `CategoryId`) from `@/lib/interfaces/coverage` are
 * used at the display layer.
 *
 * @see COVERAGE-DATA-SPEC.md
 */
export interface IntelSourceRow {
  id: string // uuid, primary key
  source_key: string // text, unique slug (e.g. 'nws-alerts')
  name: string // text, display name
  category: string // text, hazard category (e.g. 'weather', 'seismic')
  status: string // text, 'active' | 'staging' | 'quarantine' | 'disabled'
  coverage: {
    // jsonb, nullable
    geo?: string // geographic area: 'US', 'Global', 'EU', 'Asia-Pacific'
    languages?: string[] // ISO 639-1 codes: ['en']
    frequency?: string // polling cadence: '1min', '5min', '15min', '1hr'
  } | null
}

// ============================================================================
// intel_normalized
// ============================================================================

/**
 * Row type for intel_normalized table (SELECT result).
 *
 * Represents a single parsed intel item ingested from a source.
 * The `geo` field contains GeoJSON geometry (most commonly Point).
 * Coordinates follow GeoJSON convention: [longitude, latitude].
 *
 * @see COVERAGE-DATA-SPEC.md
 */
export interface IntelNormalizedRow {
  id: string // uuid, primary key
  title: string // text, alert title
  severity: string // text, 'Extreme' | 'Severe' | 'Moderate' | 'Minor' | 'Unknown'
  category: string // text, same categories as intel_sources
  source_id: string // uuid, FK to intel_sources.id
  geo: {
    // jsonb, nullable — GeoJSON geometry
    type: string // 'Point' | 'LineString' | 'Polygon'
    coordinates: number[] | number[][] | number[][][]
  } | null
  ingested_at: string // timestamptz, ISO 8601
}
