/**
 * TypeScript types for the Supabase database schema.
 *
 * These types map 1:1 to the SQL schema in supabase/migrations/.
 * They are used by the Supabase client for type-safe queries.
 *
 * In a production project, these would be auto-generated by
 * `supabase gen types typescript`. For this project, they are
 * hand-maintained to avoid a CLI dependency.
 *
 * References:
 * - 001_launch_receipts.sql
 * - 002_launch_snapshots.sql
 */

// ============================================================================
// Database Schema Type (Supabase convention)
// ============================================================================

export interface Database {
  public: {
    Tables: {
      launch_receipts: {
        Row: LaunchReceiptRow
        Insert: LaunchReceiptInsert
        Update: LaunchReceiptUpdate
      }
      launch_snapshots: {
        Row: LaunchSnapshotRow
        Insert: LaunchSnapshotInsert
        Update: LaunchSnapshotUpdate
      }
      intel_sources: {
        Row: IntelSourceRow
        Insert: Omit<IntelSourceRow, never>
        Update: Partial<IntelSourceRow>
      }
      intel_normalized: {
        Row: IntelNormalizedRow
        Insert: Omit<IntelNormalizedRow, never>
        Update: Partial<IntelNormalizedRow>
      }
      intel_bundles: {
        Row: IntelBundleRow
        Insert: Omit<IntelBundleRow, never>
        Update: Partial<IntelBundleRow>
      }
      triage_decisions: {
        Row: TriageDecisionRow
        Insert: Omit<TriageDecisionRow, never>
        Update: Partial<TriageDecisionRow>
      }
      trip_alerts: {
        Row: TripAlertRow
        Insert: Omit<TripAlertRow, never>
        Update: Partial<TripAlertRow>
      }
    }
    Views: Record<string, never>
    Functions: {
      prune_old_periodic_snapshots: {
        Args: { retention_days?: number }
        Returns: number
      }
    }
    Enums: Record<string, never>
  }
}

// ============================================================================
// launch_receipts
// ============================================================================

/** Row type: what you get back from a SELECT. */
export interface LaunchReceiptRow {
  id: string // UUID v7
  correlation_id: string | null // UUID
  source: string // ReceiptSource
  event_type: string // EventType
  severity: string // Severity
  summary: string // max 120 chars
  detail: Record<string, unknown> | null // JSONB
  location: {
    // JSONB
    semanticLevel: string
    district: string | null
    station: string | null
  }
  timestamp: string // TIMESTAMPTZ (ISO 8601)
  duration_ms: number | null
  actor: string // Actor
  ai_metadata: {
    // JSONB
    prompt: string
    reasoning: string
    confidence: number
    alternativesConsidered: string[]
    provider: string
    latencyMs: number
    modelId: string | null
  } | null
  target: Record<string, unknown> | null // JSONB (CameraTarget)
  tags: string[] | null
  snapshot_id: string | null // UUID
  created_at: string // TIMESTAMPTZ
}

/** Insert type: what you provide for an INSERT. */
export interface LaunchReceiptInsert {
  id: string
  correlation_id?: string | null
  source: string
  event_type: string
  severity: string
  summary: string
  detail?: Record<string, unknown> | null
  location: Record<string, unknown>
  timestamp: string
  duration_ms?: number | null
  actor: string
  ai_metadata?: Record<string, unknown> | null
  target?: Record<string, unknown> | null
  tags?: string[] | null
  snapshot_id?: string | null
  created_at?: string
}

/** Update type: all fields optional. */
export type LaunchReceiptUpdate = Partial<LaunchReceiptInsert>

// ============================================================================
// launch_snapshots
// ============================================================================

/** Row type: what you get back from a SELECT. */
export interface LaunchSnapshotRow {
  id: string // UUID v7
  timestamp: string // TIMESTAMPTZ
  trigger: string // 'receipt' | 'periodic' | 'manual'
  data: Record<string, unknown> // JSONB (SystemSnapshot)
  receipt_id: string | null // UUID
  created_at: string // TIMESTAMPTZ
}

/** Insert type: what you provide for an INSERT. */
export interface LaunchSnapshotInsert {
  id: string
  timestamp?: string
  trigger: string
  data: Record<string, unknown>
  receipt_id?: string | null
  created_at?: string
}

/** Update type: all fields optional. */
export type LaunchSnapshotUpdate = Partial<LaunchSnapshotInsert>

// ============================================================================
// intel_bundles
// ============================================================================

/**
 * Row type for intel_bundles table (SELECT result).
 *
 * Represents a clustered group of related intel items that have been
 * scored and optionally triaged. The `member_intel_ids` array references
 * rows in `intel_normalized`. The `primary_intel_id` is the FK to the
 * most representative member.
 *
 * Note: `categories` and `member_intel_ids` are Postgres arrays, which
 * Supabase returns as JavaScript arrays.
 */
export interface IntelBundleRow {
  id: string                          // uuid, PK
  title: string | null                // text, nullable
  summary: string | null              // text, nullable
  status: string                      // text, 'pending' | 'approved' | 'rejected'
  final_severity: string              // text, 'Extreme' | 'Severe' | 'Moderate' | 'Minor'
  categories: string[] | null         // text[], nullable
  confidence_aggregate: string | null // numeric (Supabase returns as string), nullable
  risk_score: string | null           // numeric (Supabase returns as string), nullable
  source_count: number                // integer
  intel_count: number | null          // integer, nullable
  member_intel_ids: string[]          // uuid[], NOT NULL
  primary_intel_id: string            // uuid, NOT NULL, FK to intel_normalized.id
  dedup_hash: string                  // text, NOT NULL
  representative_coordinates: {       // jsonb, nullable
    lat: number | null
    lon: number | null
  } | null
  geographic_scope: {                 // jsonb, nullable
    type: string
    radius_km?: number
    coordinates?: { lat: number | null; lon: number | null }
  } | null
  temporal_scope: {                   // jsonb, nullable
    start: string
    end: string
  } | null
  risk_details: Record<string, unknown> | null  // jsonb, nullable
  source_breakdown: Record<string, unknown> | null  // jsonb, nullable
  analyst_notes: string | null        // text, nullable
  routed_at: string | null            // timestamptz, nullable
  routed_alert_count: number | null   // integer, nullable
  created_at: string                  // timestamptz
  updated_at: string                  // timestamptz
}

// ============================================================================
// triage_decisions
// ============================================================================

/**
 * Row type for triage_decisions table (SELECT result).
 *
 * Represents an LLM or analyst verdict on an intel bundle.
 * One bundle can have multiple decisions (versioned), but typically
 * only the latest version matters.
 */
export interface TriageDecisionRow {
  id: string                           // uuid, PK
  bundle_id: string                    // uuid, FK to intel_bundles.id
  version: number                      // integer, default 1
  decision: string                     // text, 'approve' | 'reject'
  bucket: string | null                // text, nullable
  delivery_bucket: string | null       // text, nullable
  reviewer_id: string                  // uuid, FK to users.id
  note: string | null                  // text, nullable -- LLM rationale
  decided_at: string                   // timestamptz
  edited_title: string | null          // text, nullable
  edited_summary: string | null        // text, nullable
  edited_severity: string | null       // text, nullable
  edited_geo: Record<string, unknown> | null  // jsonb, nullable
  suggested_trip_ids: string[] | null  // uuid[], nullable
  selected_trip_ids: string[] | null   // uuid[], nullable
  selected_trips: string[] | null      // text[], nullable
  excluded_trips: string[] | null      // text[], nullable
  impacted_orgs: string[] | null       // text[], nullable
  diff: Record<string, unknown> | null // jsonb, nullable
}

// ============================================================================
// trip_alerts
// ============================================================================

/**
 * Row type for trip_alerts table (SELECT result).
 * Currently 0 rows in production — included for completeness.
 */
export interface TripAlertRow {
  id: string                           // uuid, PK
  bundle_id: string | null             // uuid, nullable, FK to intel_bundles.id
  trip_id: string                      // text, NOT NULL
  org_id: string                       // text, NOT NULL
  delivery_bucket: string | null       // text, nullable
  routed_by: string | null             // text, nullable
  routed_at: string | null             // timestamptz, nullable
  requires_acknowledgment: boolean | null
  priority: string | null              // text, nullable
  status: string | null                // text, nullable
  relevance_score: string | null       // numeric (returned as string), nullable
  severity: string | null              // text, nullable
  category: string | null              // text, nullable
  full_summary: string | null          // text, nullable
  scoring_details: Record<string, unknown> | null
  copy_variants: Record<string, unknown> | null
  created_at: string | null            // timestamptz
  updated_at: string | null            // timestamptz
}

// ============================================================================
// intel_sources
// ============================================================================

/**
 * Row type for intel_sources table (SELECT result).
 *
 * Represents a single intelligence feed configured in TarvaRI.
 * The `status` and `category` fields use `string` (not union types) to
 * tolerate unexpected values from the database. Narrower types
 * (`SourceStatus`, `CategoryId`) from `@/lib/interfaces/coverage` are
 * used at the display layer.
 *
 * @see COVERAGE-DATA-SPEC.md
 */
export interface IntelSourceRow {
  id: string // uuid, primary key
  source_key: string // text, unique slug (e.g. 'nws-alerts')
  name: string // text, display name
  category: string // text, hazard category (e.g. 'weather', 'seismic')
  status: string // text, 'active' | 'staging' | 'quarantine' | 'disabled'
  coverage: {
    // jsonb, nullable
    geo?: string // geographic area: 'US', 'Global', 'EU', 'Asia-Pacific'
    languages?: string[] // ISO 639-1 codes: ['en']
    frequency?: string // polling cadence: '1min', '5min', '15min', '1hr'
  } | null
}

// ============================================================================
// intel_normalized
// ============================================================================

/**
 * Row type for intel_normalized table (SELECT result).
 *
 * Represents a single parsed intel item ingested from a source.
 * The `geo` field contains GeoJSON geometry (most commonly Point).
 * Coordinates follow GeoJSON convention: [longitude, latitude].
 *
 * @see COVERAGE-DATA-SPEC.md
 */
export interface IntelNormalizedRow {
  id: string // uuid, primary key
  title: string // text, alert title
  severity: string // text, 'Extreme' | 'Severe' | 'Moderate' | 'Minor' | 'Unknown'
  category: string // text, same categories as intel_sources
  source_id: string // uuid, FK to intel_sources.id
  geo: {
    // jsonb, nullable — GeoJSON geometry
    type: string // 'Point' | 'LineString' | 'Polygon'
    coordinates: number[] | number[][] | number[][][]
  } | null
  ingested_at: string // timestamptz, ISO 8601
}
