'use client'

/**
 * TanStack Query hooks for geographic threat summaries.
 *
 * Fetches AI-generated periodic geographic summaries from the TarvaRI
 * backend API at two endpoints:
 * - `/console/summaries/latest` — most recent summary for a given scope
 * - `/console/summaries` — filtered summary history
 *
 * Two hooks are exported because they serve distinct caching strategies:
 * `useLatestGeoSummary` polls at 120s for ambient freshness while the
 * panel is open; `useGeoSummaryHistory` fetches on demand without polling.
 *
 * @module use-geo-summaries
 * @see WS-4.2
 * @see AD-3 (560px slide-over panel)
 * @see AD-7 (11-region taxonomy)
 */

import { useQuery, keepPreviousData, type UseQueryResult } from '@tanstack/react-query'
import { tarvariGet } from '@/lib/tarvari-api'
import { DATA_MODE } from '@/lib/data-mode'
import { fetchGeoSummariesFromSupabase } from '@/lib/supabase/queries'
import type { GeoLevel, ThreatLevel, TrendDirection, SummaryType } from '@/lib/interfaces/coverage'

// ============================================================================
// API types (snake_case, local)
// ============================================================================

interface ApiKeyEvent {
  title: string
  severity: string
  /** May be present if the backend includes it; absent in current API. */
  category?: string
  /** May be present if the backend includes it; absent in current API. */
  timestamp?: string
  /** Backend sends priority (critical/high/medium/low) instead of category. */
  priority?: string
  /** Backend sends description instead of timestamp. */
  description?: string
}

interface ApiStructuredBreakdown {
  threats_by_category?: Record<string, number>
  severity_distribution?: Record<string, number>
  key_events?: ApiKeyEvent[]
  risk_trend?: string
  recommendations?: string[]
  watch_items?: string[]
}

interface ApiGeoSummary {
  id: string
  geo_level: string
  geo_key: string
  summary_type: string
  threat_level?: string
  summary_text: string
  structured_breakdown: ApiStructuredBreakdown | string
  generated_at: string
  validated_at: string | null
}

interface ApiSummariesResponse {
  items: ApiGeoSummary[]
  total_count?: number
}

// ============================================================================
// Exported types
// ============================================================================

/** A notable event within a geographic summary period. */
export interface KeyEvent {
  /** Brief title or headline of the event. */
  title: string
  /** Category of the event (e.g., 'conflict', 'weather'). */
  category: string
  /** Severity of the event. */
  severity: string
  /** ISO 8601 timestamp of when the event occurred or was reported. */
  timestamp: string
}

/**
 * Quantitative and qualitative breakdown of a geographic summary.
 *
 * @see WS-4.3 — GeoSummaryPanel renders each section as a sub-component.
 */
export interface StructuredBreakdown {
  /** Alert counts keyed by category ID (e.g., { seismic: 12, conflict: 5 }). */
  threatsByCategory: Record<string, number>
  /** Alert counts keyed by severity level (e.g., { Extreme: 2, Severe: 5 }). */
  severityDistribution: Record<string, number>
  /** Notable events within the summary period. Ordered by significance. */
  keyEvents: KeyEvent[]
  /** Directional risk trend compared to the previous period. */
  riskTrend: TrendDirection
  /** Actionable recommendations for the geographic scope. */
  recommendations: string[]
}

/**
 * Normalized geographic threat summary.
 *
 * @see WS-4.3 — Primary data shape consumed by GeoSummaryPanel.
 * @see AD-3 — Slide-over panel displaying hierarchical threat assessments.
 * @see AD-7 — 11 travel-security geographic regions.
 */
export interface GeoSummary {
  /** Unique identifier for this summary. */
  id: string
  /** Geographic hierarchy level of this summary. */
  geoLevel: GeoLevel
  /** Geographic scope key (e.g., 'world', 'middle-east', 'TR'). */
  geoKey: string
  /** Summary type: 'hourly' for delta updates, 'daily' for comprehensive briefs. */
  summaryType: SummaryType
  /** Overall threat assessment level for this geographic scope. */
  threatLevel: ThreatLevel
  /** Narrative summary text — the executive brief. */
  summaryText: string
  /** Quantitative and qualitative breakdown of the threat landscape. */
  structuredBreakdown: StructuredBreakdown
  /** ISO 8601 timestamp of when this summary was generated by the AI pipeline. */
  generatedAt: string
  /** ISO 8601 timestamp of when a human analyst validated this summary. Null if not yet validated. */
  validatedAt: string | null
}

// ============================================================================
// Query key factory
// ============================================================================

/**
 * Parameterized query key factory for geographic summary data.
 *
 * Generates structured keys for targeted cache management:
 * - `all` — invalidate all geo summary caches at once
 * - `latest(level, key)` — per-scope latest summary cache
 * - `history(level, key, type)` — per-scope + type history cache
 *
 * @see WS-4.2 D-1 — Parameterized query key pattern.
 */
export const GEO_SUMMARY_QUERY_KEYS = {
  all: ['geo-summary'] as const,
  latest: (geoLevel: GeoLevel, geoKey: string) =>
    ['geo-summary', 'latest', geoLevel, geoKey] as const,
  history: (geoLevel: GeoLevel, geoKey: string, type: SummaryType) =>
    ['geo-summary', 'history', geoLevel, geoKey, type] as const,
} as const

// ============================================================================
// Normalizer
// ============================================================================

/** Map backend risk_trend vocabulary to TrendDirection (Conflict 5 resolution). */
function normalizeRiskTrend(raw: string): TrendDirection {
  if (raw === 'increasing') return 'up'
  if (raw === 'decreasing') return 'down'
  // Accept 'up'/'down'/'stable' directly as well
  if (raw === 'up' || raw === 'down') return raw
  return 'stable'
}

/**
 * Derive threat level from severity distribution when not provided by API.
 * Uses the highest severity with a non-zero count.
 */
function deriveThreatLevel(severityDist: Record<string, number>): ThreatLevel {
  if ((severityDist['Extreme'] ?? 0) > 0) return 'CRITICAL'
  if ((severityDist['Severe'] ?? 0) > 0) return 'HIGH'
  if ((severityDist['Moderate'] ?? 0) > 0) return 'ELEVATED'
  if ((severityDist['Minor'] ?? 0) > 0) return 'MODERATE'
  return 'LOW'
}

function normalizeGeoSummary(api: ApiGeoSummary): GeoSummary {
  // Defensive structured_breakdown parsing (WS-4.2 D-3)
  let breakdown: ApiStructuredBreakdown
  if (typeof api.structured_breakdown === 'string') {
    console.warn(
      '[use-geo-summaries] structured_breakdown arrived as string — expected parsed object. Applying JSON.parse().',
    )
    breakdown = JSON.parse(api.structured_breakdown) as ApiStructuredBreakdown
  } else {
    breakdown = api.structured_breakdown
  }

  const severityDist = breakdown.severity_distribution ?? {}

  return {
    id: api.id,
    geoLevel: api.geo_level as GeoLevel,
    geoKey: api.geo_key,
    summaryType: api.summary_type as SummaryType,
    threatLevel: (api.threat_level as ThreatLevel) ?? deriveThreatLevel(severityDist),
    summaryText: api.summary_text,
    structuredBreakdown: {
      threatsByCategory: breakdown.threats_by_category ?? {},
      severityDistribution: severityDist,
      keyEvents: (breakdown.key_events ?? []).map((e) => ({
        title: e.title,
        category: e.category ?? e.priority ?? 'unknown',
        severity: e.severity,
        timestamp: e.timestamp ?? api.generated_at,
      })),
      riskTrend: normalizeRiskTrend(breakdown.risk_trend ?? 'stable'),
      recommendations: breakdown.recommendations ?? [],
    },
    generatedAt: api.generated_at,
    validatedAt: api.validated_at,
  }
}

// ============================================================================
// Query functions
// ============================================================================

async function fetchLatestSummary(
  geoLevel: GeoLevel,
  geoKey: string,
): Promise<GeoSummary | null> {
  // The API returns { items: [...] } even for /latest — take the first item
  const data = await tarvariGet<ApiSummariesResponse | ApiGeoSummary>('/console/summaries/latest', {
    geo_level: geoLevel,
    geo_key: geoKey,
  })

  // Handle both response shapes: { items: [...] } or direct object
  if ('items' in data && Array.isArray(data.items)) {
    if (data.items.length === 0) {
      return null
    }
    return normalizeGeoSummary(data.items[0])
  }

  return normalizeGeoSummary(data as ApiGeoSummary)
}

async function fetchSummaryHistory(
  geoLevel: GeoLevel,
  geoKey: string,
  type: SummaryType,
): Promise<GeoSummary[]> {
  const data = await tarvariGet<ApiSummariesResponse>('/console/summaries', {
    geo_level: geoLevel,
    geo_key: geoKey,
    type,
  })
  return (data.items ?? []).map(normalizeGeoSummary)
}

// ============================================================================
// Hooks
// ============================================================================

/**
 * Fetch the latest geographic threat summary for a given scope.
 * Polls every 120s. staleTime 60s.
 *
 * Pass `null` for either parameter to disable fetching (panel closed / no scope).
 *
 * @see WS-4.2
 * @see WS-4.3 — Primary data source for GeoSummaryPanel content.
 */
export function useLatestGeoSummary(
  geoLevel: GeoLevel | null,
  geoKey: string | null,
): UseQueryResult<GeoSummary | null> {
  return useQuery<GeoSummary | null>({
    queryKey: GEO_SUMMARY_QUERY_KEYS.latest(geoLevel!, geoKey!),
    queryFn: async () => {
      if (DATA_MODE === 'supabase') {
        const rows = await fetchGeoSummariesFromSupabase()
        const match = rows.find((r) => r.geo_level === geoLevel && r.geo_key === geoKey)
        return match ? normalizeGeoSummary(match as ApiGeoSummary) : null
      }
      return fetchLatestSummary(geoLevel!, geoKey!)
    },
    enabled: geoLevel != null && geoKey != null,
    staleTime: 60_000,
    refetchInterval: 120_000,
    placeholderData: keepPreviousData,
    retry: 1,
  })
}

/**
 * Fetch geographic summary history for a given scope and type.
 * No polling — fetched on demand. staleTime 120s.
 *
 * Pass `null` for any parameter to disable fetching.
 *
 * @see WS-4.2
 * @see WS-4.3 — Data source for "What's Changed" section.
 */
export function useGeoSummaryHistory(
  geoLevel: GeoLevel | null,
  geoKey: string | null,
  type: SummaryType | null,
): UseQueryResult<GeoSummary[]> {
  return useQuery<GeoSummary[]>({
    queryKey: GEO_SUMMARY_QUERY_KEYS.history(geoLevel!, geoKey!, type!),
    queryFn: async () => {
      if (DATA_MODE === 'supabase') {
        const rows = await fetchGeoSummariesFromSupabase()
        return rows
          .filter((r) => r.geo_level === geoLevel && r.geo_key === geoKey && r.summary_type === type)
          .map((r) => normalizeGeoSummary(r as ApiGeoSummary))
      }
      return fetchSummaryHistory(geoLevel!, geoKey!, type!)
    },
    enabled: geoLevel != null && geoKey != null && type != null,
    staleTime: 120_000,
    refetchInterval: false,
    placeholderData: keepPreviousData,
    retry: 1,
  })
}

/**
 * Fetch ALL available geographic summaries (unfiltered).
 * Returns a normalized array for the filter/browse UI.
 * Polls every 120s. staleTime 90s.
 */
export function useAllGeoSummaries(enabled: boolean): UseQueryResult<GeoSummary[]> {
  return useQuery<GeoSummary[]>({
    queryKey: ['geo-summary', 'all-index', DATA_MODE],
    queryFn: async () => {
      if (DATA_MODE === 'supabase') {
        const rows = await fetchGeoSummariesFromSupabase()
        return rows.map((r) => normalizeGeoSummary(r as ApiGeoSummary))
      }
      const data = await tarvariGet<ApiSummariesResponse>('/console/summaries')
      return (data.items ?? []).map(normalizeGeoSummary)
    },
    enabled,
    staleTime: 90_000,
    refetchInterval: 120_000,
    retry: 1,
  })
}
