-- =============================================================================
-- Migration 001: launch_receipts
--
-- The 12-field receipt schema from the AIA assessment, extended with target,
-- tags, and snapshot_id for receipt rehydration.
--
-- References:
-- - AD-6 (Receipt System)
-- - WS-1.7 LaunchReceipt interface
-- - Gap #5 (Launch Data Storage)
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Receipt source enum: 'launch' or one of the 6 app identifiers.
-- Using CHECK constraint instead of ENUM type for easier extensibility.
-- New apps can be added without a migration.
CREATE TABLE IF NOT EXISTS launch_receipts (
  -- Field 1: UUID v7 primary key (time-sortable).
  -- Generated by the application, not the database, to ensure v7 format.
  id              UUID PRIMARY KEY,

  -- Field 2: Correlation ID linking related events across Launch + apps.
  -- NULL for uncorrelated events.
  correlation_id  UUID,

  -- Field 3: Source of the event.
  -- 'launch' for Launch-generated events; app identifier for observed app events.
  source          TEXT NOT NULL
                  CHECK (source IN (
                    'launch',
                    'agent-builder',
                    'tarva-chat',
                    'project-room',
                    'tarva-core',
                    'tarva-erp',
                    'tarva-code'
                  )),

  -- Field 4: Event type classification for Evidence Ledger faceted filtering.
  event_type      TEXT NOT NULL
                  CHECK (event_type IN (
                    'navigation',
                    'action',
                    'error',
                    'approval',
                    'system'
                  )),

  -- Field 5: Severity level for Evidence Ledger faceted filtering.
  severity        TEXT NOT NULL
                  CHECK (severity IN (
                    'info',
                    'warning',
                    'error',
                    'critical'
                  )),

  -- Field 6: Human-readable summary, max 120 characters.
  summary         TEXT NOT NULL
                  CHECK (char_length(summary) <= 120),

  -- Field 7: Structured detail payload. App-specific. Rendered as collapsible
  -- raw data in the Evidence Ledger.
  detail          JSONB,

  -- Field 8: Spatial context -- where in the Launch the event originated.
  -- Schema: { "semanticLevel": "Z0"|"Z1"|"Z2"|"Z3",
  --           "district": AppIdentifier | null,
  --           "station": string | null }
  location        JSONB NOT NULL,

  -- Field 9: ISO 8601 timestamp with milliseconds.
  -- Application-provided (not DEFAULT now()) to preserve exact client-side timing.
  timestamp       TIMESTAMPTZ NOT NULL,

  -- Field 10: Duration for events that span time (ms). NULL for instantaneous.
  duration_ms     INTEGER
                  CHECK (duration_ms IS NULL OR duration_ms >= 0),

  -- Field 11: Actor attribution.
  actor           TEXT NOT NULL
                  CHECK (actor IN ('human', 'ai', 'system')),

  -- Field 12: AI rationale metadata. NULL for human/system actions.
  -- Schema: { "prompt": string, "reasoning": string, "confidence": number,
  --           "alternativesConsidered": string[], "provider": string,
  --           "latencyMs": number, "modelId": string | null }
  ai_metadata     JSONB,

  -- Extension: Camera target for receipt rehydration navigation.
  -- Stores the CameraTarget discriminated union so clicking a receipt
  -- can navigate the viewport to the action's context.
  -- Schema: { "type": "position"|"district"|"station"|"home"|"constellation",
  --           ...type-specific fields }
  target          JSONB,

  -- Extension: Searchable tags for faceted filtering.
  -- Populated by station actions with [districtId, stationName, actionId].
  tags            TEXT[],

  -- Extension: Links to the system snapshot captured at receipt creation time.
  -- Used by Evidence Ledger for "then vs. now" metric comparison.
  snapshot_id     UUID,

  -- Audit metadata.
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Primary query pattern: chronological timeline (newest first).
CREATE INDEX idx_receipts_timestamp
  ON launch_receipts (timestamp DESC);

-- Faceted filtering: source app.
CREATE INDEX idx_receipts_source
  ON launch_receipts (source);

-- Faceted filtering: event type.
CREATE INDEX idx_receipts_event_type
  ON launch_receipts (event_type);

-- Faceted filtering: severity.
CREATE INDEX idx_receipts_severity
  ON launch_receipts (severity);

-- Faceted filtering: actor.
CREATE INDEX idx_receipts_actor
  ON launch_receipts (actor);

-- Correlation chain lookup.
CREATE INDEX idx_receipts_correlation
  ON launch_receipts (correlation_id)
  WHERE correlation_id IS NOT NULL;

-- Snapshot linkage for rehydration.
CREATE INDEX idx_receipts_snapshot
  ON launch_receipts (snapshot_id)
  WHERE snapshot_id IS NOT NULL;

-- GIN index on tags array for @> (contains) queries.
CREATE INDEX idx_receipts_tags
  ON launch_receipts USING GIN (tags);

-- Full-text search on summary.
-- Uses English configuration for stemming and stop words.
CREATE INDEX idx_receipts_summary_fts
  ON launch_receipts USING GIN (to_tsvector('english', summary));

-- District filtering via JSONB path.
CREATE INDEX idx_receipts_district
  ON launch_receipts ((location->>'district'));

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE launch_receipts ENABLE ROW LEVEL SECURITY;

-- Localhost single-user tool: allow all operations for any authenticated user.
-- The anon key provides access. No multi-tenant isolation needed.
CREATE POLICY "Allow all operations on launch_receipts"
  ON launch_receipts
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------

COMMENT ON TABLE launch_receipts IS
  'Immutable audit log of meaningful Launch events. 12-field AIA schema + extensions.';
COMMENT ON COLUMN launch_receipts.id IS
  'UUID v7 (time-sortable). Generated by the application.';
COMMENT ON COLUMN launch_receipts.correlation_id IS
  'Links related events across Launch and external apps.';
COMMENT ON COLUMN launch_receipts.source IS
  'Origin: launch for Launch-generated, app identifier for observed app events.';
COMMENT ON COLUMN launch_receipts.event_type IS
  'Classification for Evidence Ledger faceted filtering.';
COMMENT ON COLUMN launch_receipts.severity IS
  'Urgency level for Evidence Ledger faceted filtering.';
COMMENT ON COLUMN launch_receipts.summary IS
  'Human-readable summary, max 120 characters.';
COMMENT ON COLUMN launch_receipts.detail IS
  'Structured JSONB payload, app-specific.';
COMMENT ON COLUMN launch_receipts.location IS
  'Spatial context: { semanticLevel, district, station }.';
COMMENT ON COLUMN launch_receipts.timestamp IS
  'Client-side ISO 8601 timestamp with milliseconds.';
COMMENT ON COLUMN launch_receipts.duration_ms IS
  'Duration in ms for time-spanning events. NULL for instantaneous.';
COMMENT ON COLUMN launch_receipts.actor IS
  'Attribution: human, ai, or system.';
COMMENT ON COLUMN launch_receipts.ai_metadata IS
  'AI rationale fields: prompt, reasoning, confidence, alternatives, provider, latency.';
COMMENT ON COLUMN launch_receipts.target IS
  'CameraTarget for receipt rehydration navigation.';
COMMENT ON COLUMN launch_receipts.tags IS
  'Searchable tags array for faceted filtering.';
COMMENT ON COLUMN launch_receipts.snapshot_id IS
  'FK to launch_snapshots for then-vs-now metric comparison.';
