-- =============================================================================
-- Migration 002: launch_snapshots
--
-- Stores serialized SystemSnapshot objects for receipt rehydration
-- (metric comparison: "then vs. now") and periodic system state capture.
--
-- References:
-- - AD-6 (Receipt System -- rehydration metric comparison)
-- - WS-1.7 SystemSnapshot interface
-- - combined-recommendations.md Phase 3 Work Area 1
-- =============================================================================

CREATE TABLE IF NOT EXISTS launch_snapshots (
  -- UUID v7 primary key (time-sortable).
  id              UUID PRIMARY KEY,

  -- ISO 8601 timestamp of snapshot capture.
  timestamp       TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- What triggered this snapshot.
  -- 'receipt': captured at receipt creation time (linked to a specific receipt).
  -- 'periodic': captured on the 30-second polling interval.
  -- 'manual': captured by explicit user or system request.
  trigger         TEXT NOT NULL
                  CHECK (trigger IN ('receipt', 'periodic', 'manual')),

  -- The serialized SystemSnapshot.
  -- Schema matches WS-1.7 SystemSnapshot:
  -- {
  --   "apps": Record<AppIdentifier, AppState>,
  --   "globalMetrics": { alertCount, activeWork, systemPulse },
  --   "timestamp": ISOTimestamp
  -- }
  data            JSONB NOT NULL,

  -- Optional link to the receipt that triggered this snapshot.
  -- NULL for periodic and manual snapshots.
  receipt_id      UUID,

  -- Audit metadata.
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Primary query: chronological (newest first).
CREATE INDEX idx_snapshots_timestamp
  ON launch_snapshots (timestamp DESC);

-- Lookup by trigger type (for periodic cleanup).
CREATE INDEX idx_snapshots_trigger
  ON launch_snapshots (trigger);

-- Lookup by receipt (for rehydration metric comparison).
CREATE INDEX idx_snapshots_receipt
  ON launch_snapshots (receipt_id)
  WHERE receipt_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE launch_snapshots ENABLE ROW LEVEL SECURITY;

-- Localhost single-user tool: allow all operations.
CREATE POLICY "Allow all operations on launch_snapshots"
  ON launch_snapshots
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- Foreign Keys (deferred to avoid circular dependency)
-- ---------------------------------------------------------------------------

-- Snapshot -> Receipt (optional back-reference).
-- Not enforced as a hard FK because receipts and snapshots are created
-- in the same transaction and order may vary. The application ensures
-- referential integrity.

-- Receipt -> Snapshot (forward reference).
-- Added here because launch_snapshots table now exists.
ALTER TABLE launch_receipts
  ADD CONSTRAINT fk_receipts_snapshot
  FOREIGN KEY (snapshot_id) REFERENCES launch_snapshots(id)
  ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------

COMMENT ON TABLE launch_snapshots IS
  'System state captures for receipt rehydration metric comparison.';
COMMENT ON COLUMN launch_snapshots.id IS
  'UUID v7 (time-sortable). Generated by the application.';
COMMENT ON COLUMN launch_snapshots.trigger IS
  'What caused this snapshot: receipt, periodic, or manual.';
COMMENT ON COLUMN launch_snapshots.data IS
  'Serialized SystemSnapshot JSONB matching WS-1.7 SystemSnapshot interface.';
COMMENT ON COLUMN launch_snapshots.receipt_id IS
  'Optional back-reference to the receipt that triggered this snapshot.';

-- ---------------------------------------------------------------------------
-- Periodic Snapshot Cleanup (optional)
-- ---------------------------------------------------------------------------

-- Periodic snapshots older than 30 days can be pruned to save storage.
-- Receipt-linked snapshots are kept indefinitely (as long as the receipt exists).
-- This is a helper function, not auto-scheduled. Call manually or via cron.
CREATE OR REPLACE FUNCTION prune_old_periodic_snapshots(retention_days INTEGER DEFAULT 30)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM launch_snapshots
  WHERE trigger = 'periodic'
    AND timestamp < now() - (retention_days || ' days')::INTERVAL;
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

COMMENT ON FUNCTION prune_old_periodic_snapshots IS
  'Removes periodic snapshots older than retention_days. Receipt-linked snapshots are preserved.';
